apiVersion: v1
kind: Service
metadata:
  name: station-service
  labels:
    app: station-service
spec:
  selector:
    app: station-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP