apiVersion: apps/v1
kind: Deployment
metadata:
  name: station-deployment
  labels:
    app: station-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: station-service
  template:
    metadata:
      labels:
        app: station-service
    spec:
      containers:
        - name: station-container
          # IMPORTANTE: Se hai buildato la v2 come ti ho suggerito, scrivi v2 qui!
          # Se stai ancora usando la v1 (e l'hai ricaricata con minikube image load), lascia v1.
          image: acmemobility-station:v5  
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
            - name: NATS_URL
              value: "nats://fleet-nats:4222"
            
            # --- CORREZIONE QUI SOTTO ---
            # Uniamo tutte le opzioni Java in un'unica stringa separata da spazi.
            # 1. Limite RAM (per evitare crash)
            # 2. Seed Demo (per caricare S01, S02...)
            # 3. TTL (configurazione extra)
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75.0 -Dstation.seed.demo=true -Dstation.reservation.ttl.minutes=60"

          # Disabilitiamo i controlli per ora
          # livenessProbe: ...
          # readinessProbe: ...

          # Risorse commentate per evitare limiti stretti
          # resources: ...

---
apiVersion: v1
kind: Service
metadata:
  name: station-service
  labels:
    app: station-service
spec:
  selector:
    app: station-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP